version: '3.8'
services:
  frontend:
    image: ghcr.io/mibitech/lojaluzdointerior:latest   # atualizado pelo CI com tag SHA
    environment:
      - NODE_ENV=production
      - DEBUG=false
    expose:
      - 80
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.loja3724.rule=Host(`lojaluzdointerior.mibitech.com.br`) || Host(`www.lojaluzdointerior.mibitech.com.br`)"
        - "traefik.http.routers.loja3724.entrypoints=websecure"
        - "traefik.http.routers.loja3724.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.loja3724.loadbalancer.server.port=80"
        - "traefik.http.routers.loja3724.priority=1"
        - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.services.loja3724.loadbalancer.passHostHeader=true"
        - "traefik.http.routers.loja3724.middlewares=sslheader"
    networks:
      - rede_mibi

networks:
  rede_mibi:
    external: true
